#!/usr/bin/env php

<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

require COMPOSER_INSTALL;

use Shieldfy\Queue\ShieldfyJob;

(new ShieldfyJob())->run();